### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [snsmith92/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by snsmith92** [comment]
Hi @Mikeysax ! Thanks for the feedback. You can check my latest Git commit to see where I added the mobile meta tag. Let me know what you think!

**Comment by Mikeysax** [comment]
:+1:
